# # Install Docker
# RUN curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh 
# ADD https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker /etc/bash_completion.d/docker.sh
# # In new Docker versions, docker-compose comes built-in with docker. "docker compose" is the new command. "docker-compose" is deprecated. Use alias
# RUN echo "alias docker-compose='docker compose'" >> /root/.bashrc \
#     && echo "alias docker-compose='docker compose'" >> /etc/bash.bashrc